version: 2
jobs:
  check:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx4096m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "feature/config/build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Get Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "core/build.gradle" }}-{{ checksum  "feature/config/build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: feature/config/build/reports
          destination: feature/config/reports
      - store_artifacts:
          path: app/build/reports
          destination: app/reports
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: feature/config/build/test-results
      - store_test_results:
          path: app/build/test-results
workflows:
  version: 2
  workflow:
    jobs:
      - check
